package com.gshow.mapper.scott;

import com.gshow.domain.entity.scott.EmpEntity;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface EmpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jan 03 21:06:36 JST 2023
     */
    int deleteByPrimaryKey(Short empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jan 03 21:06:36 JST 2023
     */
    int insert(EmpEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jan 03 21:06:36 JST 2023
     */
    EmpEntity selectByPrimaryKey(Short empno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jan 03 21:06:36 JST 2023
     */
    List<EmpEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SCOTT.EMP
     *
     * @mbg.generated Tue Jan 03 21:06:36 JST 2023
     */
    int updateByPrimaryKey(EmpEntity record);
}